razorpay:
  key: rzp_test_SJYhW60LIxHLwK
  secret: Xw75iYQJQqQabARSsxhNhkYb
  webhook-secret: xxxxxx

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    username: root
    password: kprai@07
  jpa:
    hibernate:
      ddl-auto: update

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans