razorpay:
  key: rzp_test_xxxx
  secret: xxxxx
  webhook-secret: xxxxxx

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    username: root
    password: kprai@07
  jpa:
    hibernate:
      ddl-auto: update